AvdId = $AVD_ID
image.sysdir.1 = $AVD_SYSDIR
avd.ini.encoding = UTF-8
disk.dataPartition.size = 6G
fastboot.forceColdBoot = yes
PlayStore.enabled = false

hw.accelerometer = yes
hw.cpu.arch = $AVD_ARCH
# Disable audio
hw.audioInput = no
hw.audioOutput = no
hw.battery = yes
# The emulator tries to talk with port 1970 on the host when the
# 'multitouch' (the default) is set.
hw.screen = touch
hw.camera.back = emulated
hw.camera.front = emulated
hw.dPad = no
hw.gps = yes
hw.gpu.enabled = yes
hw.gpu.mode = auto
hw.cpu.ncore = 4
hw.gsmModem = true
hw.gyroscope = true
hw.initialOrientation = Portrait
hw.keyboard = yes
hw.ramSize = 4096
# Display size
hw.lcd.width = 600
hw.lcd.height = 1180
hw.lcd.density = 320
